name: Deploy Docs to S3

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      BUCKET_NAME: ${{ vars.BUCKET_NAME }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Sync docs to S3
        run: |
          aws s3 sync docs/ s3://${BUCKET_NAME}/ \
            --delete
